name:                relativistic-asteroids
version:             0.1.0.1
github:              "ehofreiter/relativistic-asteroids"
license:             BSD3
author:              "Eric W. Hofreiter"
maintainer:          "Eric W. Hofreiter"
copyright:           "Copyright Eric W. Hofreiter (c) 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Classic Asteroids clone but with relativistic physics.
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ehofreiter/relativistic-asteroids#readme>

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.4.2 && < 1
- containers >= 0.5.6.2 && < 1
- MonadRandom
- time
- random
- vector
- linear
- lens >= 4.13 && < 5
- netwire >= 5.0.0 && < 6
- sdl2 >= 2.1 && < 3
- OpenGL
- text

library:
  source-dirs: src
  exposed-modules:
  - AsteroidsGame

executables:
  relativistic-asteroids-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relativistic-asteroids

tests:
  relativistic-asteroids-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relativistic-asteroids
